apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportingApp
spec:
  selector:
    matchLabels:
      app: reportingApp
  replicas: 2
  template:
    metadata:
      labels:
        app: reportingApp
    spec:
      containers:
      - name: reportingApp
        image: report-service:latest
        ports:
        - containerPort: 9010
